name: (TEST) SLACK POOLED


on:
  issues:
    workflow_dispatch:
    types: [opened, edited, milestoned]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Send
        uses: slackapi/slack-github-action@34c3fd73326693ef04728f8611669d918a2d781d
        with:
          channel-id: C03GW7Y6YKE
          payload: |
            {
              "text": "@${{ github.event.issue.user.login }} created a new pooled issue '${{ github.event.issue.title }}' #${{ github.event.issue.number }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A new pooled Solutions-Engineering issue has been created:\n*<${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Who:* <https://github.com/${{ github.event.issue.user.login }}|@${{ github.event.issue.user.login }}>\n*Labels:* ${{ join(github.event.issue.labels.*.name, ', ') }}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "${{ github.event.issue.user.avatar_url }}",
                    "alt_text": "github avatar"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Assign Me"
                      },
                      "style": "primary",
                      "value": "assign"
                    }
                  ]
                }
              ],
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${ github.event.issue.body }"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: '${{ secrets.SLACK_POOLED_NOTIF_TOKEN }}'
