# This is a workflow to send a simple slack notification when issue has a pooled label added to it. 
# It is managed and owned by the corp-amer-se team. Specifically @logan-porelle

name: Pooled Request Notification

on:
  issues:
    types:
      - labeled

jobs:
  slack-notification:
    if: github.event.label.name == 'pooled'
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Create message
        uses: actions/github-script@v6
        id: create-message
        with:
          script: |
            return 'New pooled issue created by @${{ github.event.issue.user.login }}\n*<${{ github.event.issue.html_url }}|#${{ github.event.issue.number }} ${{ github.event.issue.title }}>*'
      - name: Slack Send
        uses: slackapi/slack-github-action@34c3fd73326693ef04728f8611669d918a2d781d
        with:
          channel-id: ${{ env.CHANNEL_ID }}
          payload: |
            {
              "text": "New pooled issue created by @${{ github.event.issue.user.login }}",
              "blocks": [{
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ steps.create-message.outputs.result }}
                  }
                },
                {
                  "type": "actions",
                  "elements": [{
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Assign Me"
                    },
                    "style": "primary",
                    "value": "assign"
                  }]
                }
              ],
              "metadata": {
                "event_type": "issue",
                "event_payload": {
                  "number": "${{ github.event.issue.number }}",
                  "title": "${{ github.event.issue.title }}",
                  "html_url": "${{ github.event.issue.html_url }}",
                  "updated_at": "${{ github.event.issue.updated_at }}",
                  "repo_name": "${{ github.event.repository.name }}",
                  "repo_owner": "${{ github.event.repository.owner.login }}",
                  "repository_owner_id": ${{ github.repository_owner_id }}
                }
              }
            }
        env:
          CHANNEL_ID: 'C03GW7Y6YKE'
          SLACK_BOT_TOKEN: '${{ secrets.SLACK_POOLED_NOTIF_TOKEN }}'
