name: (TEST) SLACK POOLED


on:
  issues:
    workflow_dispatch:
    types: [opened, edited, milestoned]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Markdown Converter
        id: slack-md-converter
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        with:
          text: ${{ github.event.issue.body }}
      - name: Slack Send
        uses: slackapi/slack-github-action@34c3fd73326693ef04728f8611669d918a2d781d
        with:
          channel-id: C03GW7Y6YKE
          payload: |
            {
              "text": "New pooled issue created by @${{ github.event.issue.user.login }}",
              "blocks": [{
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.event.issue.user.login }}|@${{ github.event.issue.user.login }}> created a new pooled issue\n*<${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>*\nLabels:* ${{ join(github.event.issue.labels.*.name, ', ') }}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "${{ github.event.issue.user.avatar_url }}",
                    "alt_text": "github avatar"
                  }
                },
                {
                  "type": "actions",
                  "elements": [{
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Assign Me"
                    },
                    "style": "primary",
                    "value": "assign"
                  }]
                }
              ],
              "attachments": [{
                "blocks": [{
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(steps.slack-md-converter.outputs.text) || 'No description provided.' }}
                  }
                }]
              }],
              "metadata": {
                "event_type": "issue",
                "event_payload": {
                  "number": "${{ github.event.issue.number }}",
                  "title": "${{ github.event.issue.title }}",
                  "html_url": "${{ github.event.issue.html_url }}"
                }
              }
            }
        env:
          SLACK_BOT_TOKEN: '${{ secrets.SLACK_POOLED_NOTIF_TOKEN }}'
