name: (TEST) SLACK POOLED


on:
  issues:
    workflow_dispatch:
    types: [opened, edited, milestoned]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Markdown Converter
        id: slack-md-converter
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        with:
          text: ${{ github.event.issue.body }}
      - name: Create Message
        uses: actions/github-script@v6
        id: create-message
        with:
          script: |
            return '*<${{ github.event.issue.html_url }}|#${{ github.event.issue.number }} ${{ github.event.issue.title }}>*' + JSON.stringify(`${{ steps.slack-md-converter.outputs.text }}`).slice(1,-1)
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - name: Slack Send
        uses: slackapi/slack-github-action@34c3fd73326693ef04728f8611669d918a2d781d
        with:
          channel-id: C03GW7Y6YKE
          payload: |
            {
              "text": "New pooled issue created by @${{ github.event.issue.user.login }}",
              "blocks": [{
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "New pooled issue created by <https://github.com/${{ github.event.issue.user.login }}|@${{ github.event.issue.user.login }}>"
                  }
                },
                {
                  "type": "actions",
                  "elements": [{
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "Assign Me"
                    },
                    "style": "primary",
                    "value": "assign"
                  }]
                }
              ],
              "attachments": [{
                "blocks": [{
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.create-message.outputs.result }}"
                  }
                }]
              }],
              "metadata": {
                "event_type": "issue",
                "event_payload": {
                  "number": "${{ github.event.issue.number }}",
                  "title": "${{ github.event.issue.title }}",
                  "html_url": "${{ github.event.issue.html_url }}"
                }
              }
            }
        env:
          SLACK_BOT_TOKEN: '${{ secrets.SLACK_POOLED_NOTIF_TOKEN }}'
